theme: jekyll-theme-cayman
title: "Henry's Blog: What am I thinking?"
name: "Henry's Blog: What am I thinking?"
description: "Henry's Blog: What am I thinking?"


authors:
  henry:
    name: Henry QIU
    email: hejia.qiu@outlook.com
    web: https://henryjaqiu.github.io
    
